Update main.go
ogosasan/yadro pull request #3
Opened 2024-03-27 14:35 UTC by ogosasan

2024-03-28 15:58 UTC, kirreal commented
В целом уже почти хорошо, хотя, на такой строке результат не тот:
"Isn't she lovely? By the way I believe she's got it and I'd like being aroud."

2024-03-28 16:00 UTC, kirreal requested changes

2024-03-28 16:00 UTC, kirreal commented on main.go
> +			if err == nil && seen[stemmed] == nil {
Обработку ошибок лучше делать сразу, в случае ошибки stemmed будет пустой строкой, я бы порекомендовал сначала проверить ошибку и если она != nil и распечатать ошибку в лог и сделать continue

2024-04-01 07:32 UTC, vbelogrudov approved these changes
есть недочеты - можно исправить в следующих заданиях. 
Еще желательно стоп слова поместить в словарь, чтобы не пробегать по ним снова и снова при многократном стемминге

2024-04-01 07:32 UTC, vbelogrudov commented on main.go
> +	seen := make(map[string]interface{})
seen := make(map[string]bool) и потом просто проверять if ... seen[stemmed]

2024-04-01 17:29 UTC, ogosasan commented on main.go
> +	seen := make(map[string]interface{})
https://github.com/ogosasan/yadro/issues/5 
У меня изначально было map[string]bool, но сказали сделать с интерфейсом.

2024-04-04 14:34 UTC, closed without merging